### ISSUE TITLE
Missing tvb-library from requirements

### ISSUE THREAD

**Issue by liadomide** [ins-amu/virtual_aging_brain#2]
I see code in this repo having imports from `tvb.simulator`, yet I can not see `tvb-library` as a 3rd party python dependency in `requirements.txt`, or in `README` in the Installations section.
Also, I see `tvb-data` as a dependency described in README. Wouldn't be better to move it in `requirements.txt`?

**Comment by i-Zaak** [comment]
Thanks for taking a look :+1:
