### ISSUE TITLE
Missing python scripts

### ISSUE THREAD

**Issue by dyhan316** [ins-amu/virtual_aging_brain#5]
Hello again!

It appears that although the `03_vab_github_summary_data.ipynb` has the line ,`from src import data, analysis, simulation, FC_analysis, viz, Burstiness `, inside the src folder, only `data, analysis, simulation` are present. 

Could you upload the `src/FC_analysis`, `src/viz`, `src/Burstiness` ?

**Comment by i-Zaak** [comment]
Dear Danny,
 as far as I can tell, these are unused imports. I have removed them in #6 

All the best,
Jan

**Comment by dyhan316** [comment]
Dear Jan

Oh I see! Thank you!  :)

Danny
